import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import "@gov-design-system-ce/styles/lib/styles.css";
import "@gov-design-system-ce/styles/lib/layout.css";
import "@gov-design-system-ce/styles/lib/print.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={inter.className}>
        {/* Needed to correctly load icons from design system components */}
        {/* TODO: Find out if there is a better place to configure it */}
        <script
          dangerouslySetInnerHTML={{
            __html: `window.GOV_DS_CONFIG = { iconsPath: "/icons" }`,
          }}
        />
        <Navbar lang="cs" />
        {children}
      </body>
    </html>
  );
}
